image: starefossen/ruby-node:latest

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - bundle install
  script:
    - serverless deploy --stage default --verbose
  environment: production